Header and hero section
hajnaloltyan/portfolio-mv pull request #1
Opened 2023-03-22 21:49 UTC by hajnaloltyan

Portfolio site using Template 1 - Header and Hero section

- Added and installed the linter files
- Created the html structure and added the required styles
- Edited the README file

2023-03-22 22:23 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @hajnaloltyan, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 22:23 UTC, anagudelogu commented on README.md
> +
- [ ] You did a great job documenting your project! 🚀 However, please make sure that you change this link to your LICENSE file for the actual file present in your repo. 🤓 

```suggestion

This project is [MIT](./LICENSE) licensed.

```

2023-03-22 22:23 UTC, anagudelogu commented on index.html
> +        </div>
- [ ] You did a great job working on this milestone! 💯 However, I suggest you use a better markup for your social-media icons. This is kind of a list of your social media links, so it would be great if you use the HTML tags to represent just that! `<ul>` as container and `<li>` for each icon! 🤓 🔧 

something like this:

```html
<ul class="hero__icons"> 
  <li>
    <a href="https://twitter.com/HajnalOltyan" class="social-icon">
      <img
        src="./images/twitter.svg"
        alt="Twitter"
        class=""
      >
    </a>
  </li>
  <li> ... </li>
</ul>
```

2023-03-22 22:23 UTC, anagudelogu commented on style.css
> +}
- [ ] I noticed that you have multiple repeated CSS properties across your stylesheet. It would be great if you can find a way of reducing this duplication of code ♻️. Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️

From [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md):
![image](https://user-images.githubusercontent.com/77069011/200000947-9e58c4d8-fed4-45f8-a822-7828c6e713f7.png)

In this case, you could do this with flex:

```CSS
.flex {
  display: flex;
}
```

And then, use it in your HTML elements where you need a flex container:

```HTML
<div class="flex"> This is a flex container </div>
```

Please, consider fixing this! 🤓

2023-03-23 16:14 UTC, adel-gu requested changes
# Status: REQUIRE CHANGES ♻️ 

Hi @hajnaloltyan 👋🏼 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- The MIT license link is working ✔️ 
- HTML semantics are well used ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 16:14 UTC, adel-gu commented on style.css
> +  background-image: url(./images/hero-background.png);
The background image isn't responsive on some screen sizes, please be aware that the mobile screen sizes are in the range of **min 375px** to **max 768px**, in your project, all the contents are incredibly responsive except the background image for the headline section.

- [ ] Please consider fixing the responsiveness of the headline background and I highly recommend exporting multiple decoration elements from the Figma design instead of exporting the whole background 👍🏼 as one image, after that you can use [multiple backgrounds in CSS](https://www.w3schools.com/css/css3_backgrounds.asp).

### Your Design 
![image](https://user-images.githubusercontent.com/68030297/227262929-292d52c9-c8c9-41e8-807e-c93f217aa809.png)


### Figma Design 
![image](https://user-images.githubusercontent.com/68030297/227263730-e0774dfe-5241-41f1-aeea-16e60c68db15.png)

2023-03-23 17:35 UTC, hajnaloltyan commented on style.css
> +  background-image: url(./images/hero-background.png);
I thought we only needed the mobile version to be created, and that's more relevant to the desktop version

2023-03-23 21:02 UTC, adel-gu commented on style.css
> +  background-image: url(./images/hero-background.png);
Hi @hajnaloltyan 👋🏼 mobile version is a range of **min 375px** and **max 786px** 👍🏼

2023-03-23 22:15 UTC, merged