Works and About Section
hajnaloltyan/portfolio-mv pull request #2
Opened 2023-03-24 17:52 UTC by hajnaloltyan

Portfolio site using Template 1 - Works and About sections for mobile

- Created the HTML structure for the required sections
- Added the styles for them using Grid and Flexbox

- [Live Demo Link](https://hajnaloltyan.github.io/portfolio-mv)

2023-03-24 18:30 UTC, Kamba56 requested changes
Hi @hajnaloltyan, 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great use of Github workflow!👏👏👏
- [x] All linters passed
- [x] Great job deploying your page

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 18:30 UTC, Kamba56 commented on index.html
> +
- [ ] Please note that you are expected to stick to design as much as possible. This is including spacings between elements. The spaces between the elements in your cards looks less than it is on the template. KIndly improve on this please.
### Your design
![image](https://user-images.githubusercontent.com/94551484/227605934-29ed0138-eb77-4ca8-81df-183e337bdbd4.png)
### Figma
![image](https://user-images.githubusercontent.com/94551484/227606114-64b4d8bf-bd99-4adb-aea7-f140774f569e.png)

2023-03-24 18:30 UTC, Kamba56 commented on style.css
> +  margin-bottom: 12px;
- [ ] Consider adding a hover and pressed state to all your buttons as it is on the figma template. You can use the `:hover` and `:active` pseudoclasses for this.
![image](https://user-images.githubusercontent.com/94551484/227545089-c6ed521a-18ff-4bee-9e00-8f06897df79c.png)

2023-03-24 18:30 UTC, Kamba56 commented on index.html
> +
- [ ] Kindly reduce the width of this heading so it matches the figma template. You are required to stick to design as much as possible, this includes width, height, fonts, sizes, margins, and paddings.
### FIgma
![image](https://user-images.githubusercontent.com/94551484/227607050-61cbd881-2f87-41b0-8398-06e9535869db.png)
### Your design
![image](https://user-images.githubusercontent.com/94551484/227607120-39038534-6448-4dcf-b1f4-c7f3156624b7.png)

2023-03-24 18:30 UTC, Kamba56 commented on index.html
>      <title>Portfolio</title>
- [ ] I noticed your getting started section is of no help to the user. Kindly populate it so users can easily set up a local copy of your work.
![image](https://user-images.githubusercontent.com/94551484/227610127-bd37279e-f60a-4151-92f6-6b6266954d51.png)

2023-03-24 20:55 UTC, hajnaloltyan commented on index.html
> +
@Kamba56 Hi, I'm trying to add a screenshot of Figma, the design there looks the same as mine, the Text is in one line
![Screenshot from 2023-03-24 21-52-13](https://user-images.githubusercontent.com/101429702/227637974-84f735e5-0fa6-4ca4-8c0c-93165255f5c9.png)

2023-03-24 20:56 UTC, hajnaloltyan commented on index.html
> +
@Kamba56 I don't know how to put a picture here, it shows up broken, but my design looks like the Figma design, the Text is in 1 line

2023-03-24 22:09 UTC, braincee approved these changes
Hi @hajnaloltyan  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-24 22:20 UTC, merged

2023-03-25 07:46 UTC, Kamba56 commented on index.html
> +
I'm sorry about that. I made a copy of the old design, I didn't know the design has been changed. I apologize.